### PR TITLE
fix all unit tests to pass

### PR DESCRIPTION
**Pull request by Giovani-Brady**
updated xunit package to run in native visual studio test explorer, updated all unit test to pass

### CODE REVIEW

**Comment by Giovani-Brady** [comment]
@nberardi  please code review

@paulirwin  please code review

@paulirwin  What is the required number of Pull Requests necessary to be considered an "Author"?

**Comment by paulirwin** [comment]
There is no number of pull requests to become a collaborator or author on this project, or any project for that matter. Many others have contributed to this project and are not collaborators. To become a collaborator, you must show a willingness to be responsible for maintaining the project as well as being respectful of the process and others. In any open source project, that requires an amount of time to pass as we get to know each other. You first popped up on the radar of this project less than a month ago. Again let's pump the brakes a little bit. We welcome your contributions to the project but to expect to step in to a project as a collaborator/maintainer within a few days is a bit premature. As Nate can tell you, or you can see from the commit history, my first PR took 9 months to make it into the NuGet package! I hope we can move at a faster pace than that, but please have patience and let's work through these PRs and issues, get a release out the door, and re-evaluate later. I will be reviewing your PRs shortly.

**Comment by Giovani-Brady** [comment]
I am only so aggressive with these updates because yourself and @nberardi  have allowed this repository to fall into such a bad state as not being able to pass all of it's own unit tests and failed to update the repository features with the corresponding Stripe API features as they were updated.

I hope we can move all of these changes along quickly to restore the NuGet Package reputation and build out further support for missing Stripe API features in this repository.

**Comment by paulirwin** [comment]
Tests pass now, merged into master. Also removed legacy NuGet.exe since the new xunit was complaining about that and now NuGet can restore packages without that.

**Pull request merged**
