### PR TITLE
project updates and restructure

### PR DESCRIPTION
**Pull request by Giovani-Brady**
file reorganization for clearer separation of concerns

### CODE REVIEW

**Comment by nberardi** [comment]
Why the moving of the code files? Typically you want to keep them inline with your namespace.

**Comment by Giovani-Brady** [comment]
notice if you review all of the changes, the namespace is the same. the folder structure is for clarity.

**Comment by Giovani-Brady** [comment]
the unit tests updates as supposed to be a separate pull requests. my apologies.

**Comment by nberardi** [comment]
I get that the namespace is the same. I don't believe this adds any clarity. Because all the client files already differentiated by name. 

I know you are trying to add value so that you can become a contributing member. However. Rearranging the code base, updating packages, and changing the framework doesn't really add value. 

Implementing missing features and adding missing unit test cases adds value. 

--
Nick Berardi
(484) 302-0125
Sent on the go from my phone.

**Comment by Giovani-Brady** [comment]
so all of these contributions are essentially useless to yourself and this repository. correct?

**Comment by Giovani-Brady** [comment]
Are there any other technical concerns i should address is this pull requests?

**Comment by Giovani-Brady** [comment]
I am unfamiliar with the Travis CI build.

but from what I can gather from the error messaging I am unsure whether there is anything i can do to get a successful build.

Let me know if I can correct this.

Error message from build:
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)

**Comment by nberardi** [comment]
I am not sure about Travis either. It looks like we are missing a yaml file.  It looks like the changes you made are pretty good.  I would like Paul to weigh in, since he uses this library a little more actively than I do at this point.

**Comment by Giovani-Brady** [comment]
Understandable, i look forward to hearing from Paul Irwin. The sooner the better, I'd like to build out further support for the other Stripe API features this repo is missing.

**Comment by Giovani-Brady** [comment]
@paulirwin ready for code review

**Comment by paulirwin** [comment]
Regarding the Travis CI build, that was something I was attempting to set up and ran into issues, most likely since the Travis CI mono support is in beta. IIRC, I had filed a ticket with the Travis CI folks about this, but I'll take another look at it later. For now, you can ignore the warnings.

This is too large of a pull request. I agree that rearranging files at the current time is not beneficial, especially not while combined with other changes. The combination of rearranging files, updating NuGet references, changing the target framework, changing interface definitions, as well as functional changes makes this too large. 

Also, it is quite the bold move to add yourself as an author on your first pull request. Let's pump the brakes a little bit. I added myself as an author only after Nate handed the responsibility of the repo over to me.

I'm going to close this PR for the reasons above. Please submit granular PRs that correspond to and reference issues, even if you're the one creating the issue. Also, please make any PRs come from branches in your repo, rather than master. That way the branch can be automatically deleted if we accept it, then all of the latest changes flow back into your master. I look forward to your contributions, but please approach them in a patient and respectable way.

**Pull request closed without merging**
